S=str(input('Dati un sir de caractere:'))
print('a)')
print(S.count('A'))
print('b)')
print(S.replace('A','*'))
print('c)')
print(S.replace('B',''))
print('d)')
print(S.count('MA'))
print('e)')
print(S.replace('MA','TA'))
print('f)')
print(S.replace('TO',''))
print('g)')
print(S[::-1])